[package]
name = "hellostarknet"
version = "0.1.0"
cairo-version = "2.5.4"  # Or latest stable version from https://docs.swmansion.com/scarb/
description = "Hello Starknet Contract"

[dependencies]
starknet = "2.5.4"  # Match this with your cairo-version

[[target.starknet-contract]]
# No need to specify path if using default `src/lib.cairo`
